import {
  BiLinkExternal,
  BiLogoCodepen,
  BiLogoDribbble,
  BiLogoGithub,
  BiLogoGitlab,
  BiLogoInstagram,
  BiLogoLinkedinSquare,
  BiLogoStackOverflow,
  BiLogoSteam,
  BiLogoUnsplash,
  BiLogoYoutube,
} from "react-icons/bi";
import { FaFreeCodeCamp, FaProductHunt } from "react-icons/fa";
import { SiCodewars } from "react-icons/si";
import { FaRust, FaJava, FaDatabase, FaDocker, FaAws, FaNodeJs, FaReact, FaVuejs, FaScrewdriverWrench } from "react-icons/fa6";
import { SiNestjs, SiKoa, SiTauri, SiWebassembly, SiJest, SiNginx } from "react-icons/si";
import { RiNextjsLine, RiTailwindCssLine } from "react-icons/ri";

export const socialLinks = [
  {
    id: 1,
    name: "Nodejs",
    url: "https://github.com/kenjiding",
    icon: FaNodeJs,
    status: "backend",
  },
  {
    id: 2,
    name: "Rust",
    url: "https://twitter.com/kenjiding",
    icon: FaRust,
    status: "backend",
  },
  {
    id: 3,
    name: "Nestjs",
    url: "https://linkedin.com/in/kenjiding",
    icon: SiNestjs,
    status: "backend",
  },
  {
    id: 4,
    name: "Express/Koa",
    url: "https://codepen.io/kenjiding",
    icon: SiKoa,
    status: "backend",
  },
  {
    id: 3.5,
    name: "Java",
    url: "https://linkedin.com/in/kenjiding",
    icon: FaJava,
    status: "backend",
  },
  {
    id: 4.5,
    name: "Mysql/Postgres/MongoDB",
    url: "https://dribbble.com/kenjiding",
    icon: FaDatabase,
    status: "backend",
  },
  {
    id: 5,
    name: "React",
    url: "https://dribbble.com/kenjiding",
    icon: FaReact,
    status: "frontend",
  },
  {
    id: 6,
    name: "Nextjs",
    url: "https://instagram.com/kenjiding",
    icon: RiNextjsLine,
    status: "frontend",
  },
  {
    id: 7,
    name: "Vue",
    url: "https://steamcommunity.com/id/kenjiding/",
    icon: FaVuejs,
    status: "frontend",
  },
  {
    id: 8,
    name: "React Native",
    url: "https://unsplash.com/@kenjiding",
    icon: FaReact,
    status: "frontend",
  },
  {
    id: 9,
    name: "Electron / Tauri",
    url: "https://freecodecamp.org/news/author/kenjiding/",
    icon: RiTailwindCssLine,
    status: "frontend",
  },
  {
    id: 10,
    name: "Micro Front-end",
    url: "#",
    icon: SiTauri,
    status: "frontend",
  },
  {
    id: 11,
    name: "Web Assembly",
    url: "https://www.sanity.io/exchange/community/kenjiding",
    icon: SiWebassembly,
    status: "frontend",
  },
  {
    id: 12,
    name: "Webpack / Vite / TurboPack",
    url: "https://youtube.com/@kenjiding",
    icon: FaScrewdriverWrench,
    status: "frontend",
  },
  {
    id: 13,
    name: "Tailwind CSS / Headless UI",
    url: "https://app.daily.dev/kenjiding",
    icon: RiTailwindCssLine,
    status: "frontend",
  },
  {
    id: 14,
    name: "AWS",
    url: "https://www.producthunt.com/@kenjiding",
    icon: FaAws,
    status: "devOps",
  },
  {
    id: 15,
    name: "Jest / Cypress E2E",
    url: "https://stackoverflow.com/users/14021166/kenjiding",
    icon: SiJest,
    status: "devOps",
  },
  {
    id: 16,
    name: "Docker",
    url: "https://www.codewars.com/users/kenjiding",
    icon: FaDocker,
    status: "devOps",
  },
  {
    id: 17,
    name: "Nginx",
    url: "https://gitlab.com/kenjiding",
    icon: SiNginx,
    status: "devOps",
  },
];
